config/routes.rb
Numerous::Application.routes.draw do
  get "frontpages/index"

  # These should be removed and accessed using a different controller
  resources :tag_links

  controller :stories do
    get 'stories/:article_id/new_photo' => :new_photo
    get 'stories/new_article' => :new_article
    post 'stories' => :create_article
    post 'stories/:article_id/create_photo' => :create_photo
  end

  resources :users

  scope ':username', as: :user do
    resources :articles do
      resources :comments, only: :create
    end

    resources :admin, only: :index
  end

  controller :articles do
    post 'articles/:article_id/create_photo' => :create_photo
  end

  resources :tags

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  controller :photos do
    patch 'photos/:id/rotate_clockwise' => :rotate_clockwise
  end

  resources :photos do
    resources :comments, only: :create
  end

  root :to => 'frontpages#index'
end

app/views/layouts/main_bar/_general.html.slim
div class="pure-menu pure-menu-horizontal"
  a class="pure-menu-heading pure-menu-link" href="/" Word Count
  ul class="pure-menu-list"
    li class="pure-menu-item" id="articles-item"
      a class="pure-menu-link" href="/" Home
    li class="pure-menu-item" id="admin-item"
      = link_to "Login", login_url, class: "pure-menu-link"

app/views/layouts/main_bar/_logged.html.slim
/ not possible to access @user generated in application controller
- user = User.find_by_id(session[:user_id])

div class="pure-menu pure-menu-horizontal"
  a class="pure-menu-heading pure-menu-link" href="/" Word Count
  ul class="pure-menu-list"
    li class="pure-menu-item" id="articles-item"
      a class="pure-menu-link" href="/" Home
    li class="pure-menu-item" id="destinations-item"
      = link_to "My Articles", user_articles_url(user.username), class: "pure-menu-link"
    li class="pure-menu-item" id="admin-item"
      = link_to "My Account", user_admin_index_url(user.username), class: "pure-menu-link"