config/routes.rb
Numerous::Application.routes.draw do
  get "frontpages/index"

  # These should be removed and accessed using a different controller
  resources :tag_links

  controller :stories do
    get 'stories/:article_id/new_photo' => :new_photo
    get 'stories/new_article' => :new_article
    post 'stories' => :create_article
    post 'stories/:article_id/create_photo' => :create_photo
  end

  resources :users

  scope ':username', as: :user do
    resources :articles do
      resources :comments, only: :create
    end

    resources :admin, only: :index
  end

  controller :articles do
    post 'articles/:article_id/create_photo' => :create_photo
  end

  resources :tags

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  controller :photos do
    patch 'photos/:id/rotate_clockwise' => :rotate_clockwise
  end

  resources :photos do
    resources :comments, only: :create
  end

  root :to => 'frontpages#index'
end

app/models/tag_link.rb
class TagLink < ActiveRecord::Base
  # id, int, PKEY
  # tag_id, int, FKEY
  # tagable_id, int, FKEY
  # tagable_type, string
  # created_at, datetime
  # updated_at, datetime

  belongs_to :tag
  belongs_to :tagable, polymorphic: true

  def self.find_or_init(name)
  end

  def self.find_by_name(name)
    tag = Tag[name]
    self.where(tag_id: tag.id) unless tag.nil?
  end
end

app/controllers/tag_links_controller.rb
class TagLinksController < ApplicationController
  before_action :set_tag_link, only: [:show, :edit, :update, :destroy]

  # GET /tag_links
  def index
    @tag_links = TagLink.all
  end

  # GET /tag_links/1
  def show
  end

  # GET /tag_links/new
  def new
    @tag_link = TagLink.new
  end

  # GET /tag_links/1/edit
  def edit
  end

  # POST /tag_links
  def create
    @tag_link = TagLink.new(tag_link_params)

    if @tag_link.save
      redirect_to @tag_link, notice: 'Tag link was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tag_links/1
  def update
    if @tag_link.update(tag_link_params)
      redirect_to @tag_link, notice: 'Tag link was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /tag_links/1
  def destroy
    @tag_link.destroy
    redirect_to tag_links_url, notice: 'Tag link was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag_link
      @tag_link = TagLink.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_link_params
      params.require(:tag_link).permit(:tag_id, :tagable_id, :tagable_type)
    end
end

app/helpers/tag_links_helper.rb
module TagLinksHelper
end

app/views/tag_links/_form.html.erb
<%= form_for(@tag_link) do |f| %>
  <% if @tag_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag_link.errors.count, "error") %> prohibited this tag_link from being saved:</h2>

      <ul>
      <% @tag_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.text_field :tag_id %>
  </div>
  <div class="field">
    <%= f.label :tagable_id %><br>
    <%= f.text_field :tagable_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tag_links/edit.html.erb
<h1>Editing tag_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag_link %> |
<%= link_to 'Back', tag_links_path %>

app/views/tag_links/index.html.erb
<h1>Listing tag_links</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Tagable</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tag_links.each do |tag_link| %>
      <tr>
        <td><%= tag_link.tag %></td>
        <td><%= tag_link.tagable %></td>
        <td><%= link_to 'Show', tag_link %></td>
        <td><%= link_to 'Edit', edit_tag_link_path(tag_link) %></td>
        <td><%= link_to 'Destroy', tag_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag link', new_tag_link_path %>

app/views/tag_links/new.html.erb
<h1>New tag_link</h1>

<%= render 'form' %>

<%= link_to 'Back', tag_links_path %>

app/views/tag_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @tag_link.tag %>
</p>

<p>
  <strong>Tagable:</strong>
  <%= @tag_link.tagable %>
</p>

<%= link_to 'Edit', edit_tag_link_path(@tag_link) %> |
<%= link_to 'Back', tag_links_path %>